# Site settings
title: Anjue’S BLOG- A.B.
email: anjue39@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Anjue's Blog (aka AB)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://anjue39.github.io" # the base hostname & protocol for your site
twitter_username: anjue39
github_username:  anjue39
linkedin_url: "https://anjue39.github.io"
facebook_url: "https://www.facebook.com/anjue39"
flickr_url: ""
disqus_shortname: anjue39

imageurl: "https://anjue39.github.io/images"

# Build settings
markdown: kramdown
kramdown:
        math_engine: mathjax
        input: GFM
        hard_wrap: true
        syntax_highlighter_opts:
                disable: true
# _pages
include: ['_pages']

plugins:
- jekyll-admin
